"""Bootstrap 95% CI for R@1 / R@5 per (dataset, agent, backbone).

Reads `data/round2/phase4a_summary.json` (from phase4a_report_gen.py) and
adds bootstrap CI columns. Saves to `phase4a_with_ci.json` and writes a
paper-grade markdown table at `phase4a_REPORT_with_ci.md`.

Bootstrap: 10000 resamples per cell. Uses bootstrap percentile method.
"""
from __future__ import annotations
import json, sys
from pathlib import Path
from collections import defaultdict
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

def bootstrap_ci(hits: int, n: int, n_boot: int = 10000) -> tuple[float, float]:
    """Bootstrap 95% percentile CI for a binomial proportion."""
    if n == 0: return (0.0, 0.0)
    import random
    rng = random.Random(42)
    p = hits / n
    rates = []
    for _ in range(n_boot):
        # Sample n cases with replacement: count hits
        s = sum(1 for _ in range(n) if rng.random() < p)
        rates.append(s / n)
    rates.sort()
    return (rates[int(n_boot * 0.025)], rates[int(n_boot * 0.975)])

def main():
    with open('data/round2/phase4a_summary.json') as f:
        stats = json.load(f)

    out = {}
    for key, s in stats.items():
        if s['ok'] == 0:
            out[key] = {**s, "r1v_ci": None, "r5v_ci": None, "r1v": 0, "r5v": 0}
            continue
        r1v = s['h1v'] / s['ok']
        r5v = s['h5v'] / s['ok']
        ci1 = bootstrap_ci(s['h1v'], s['ok'], 5000)
        ci5 = bootstrap_ci(s['h5v'], s['ok'], 5000)
        out[key] = {**s, "r1v": r1v, "r5v": r5v, "r1v_ci": ci1, "r5v_ci": ci5}

    Path('data/round2/phase4a_with_ci.json').write_text(json.dumps(out, indent=2))

    # Build markdown table
    md = ["# Phase 4a with Bootstrap 95% CI", "",
          "Generated by `scripts/phase4a_ci_bootstrap.py`", ""]
    bb_label = {
        'google_gemini-3-flash-preview-20251217':'Gemini Flash',
        'deepseek_deepseek-v4-pro':'DS V4-Pro',
        'deepseek_deepseek-v4-flash':'DS V4-Flash',
        'openai_gpt-5':'GPT-5 min',
        'vc_rdagent-offline-v1':'offline',
        'lirical-2.4.0':'classical',
    }
    by_ds_agent = defaultdict(dict)
    for key, s in out.items():
        ds, ag, bb = key.split('|')
        by_ds_agent[(ds, ag)][bb] = s

    for ds in ('phenopacket_store','rarearena_rds','rarebench','mimic_diverse'):
        md.append(f"\n## {ds}\n")
        md.append("| Agent | Backbone | n_ok | R@1 (95% CI) | R@5 (95% CI) |")
        md.append("|---|---|---|---|---|")
        agents = sorted({a for (d,a) in by_ds_agent if d == ds})
        for ag in agents:
            for bb, label in bb_label.items():
                s = by_ds_agent.get((ds,ag), {}).get(bb)
                if not s: continue
                if s['ok'] == 0: continue
                ci1 = s['r1v_ci']
                ci5 = s['r5v_ci']
                md.append(
                    f"| `{ag}` | {label} | {s['ok']}/{s['ok']+s['err']} | "
                    f"**{s['r1v']:.2f}** [{ci1[0]:.2f}-{ci1[1]:.2f}] | "
                    f"**{s['r5v']:.2f}** [{ci5[0]:.2f}-{ci5[1]:.2f}] |"
                )

    Path('data/round2/phase4a_REPORT_with_ci.md').write_text("\n".join(md))
    print(f"Wrote phase4a_with_ci.json + phase4a_REPORT_with_ci.md ({len(md)} lines)")

if __name__ == "__main__":
    main()
